name: example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  syntax_highlight: ^0.4.0
  google_fonts: ^6.2.1

  flutter_confetti:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10
  watcher: ^1.1.0

flutter:
  uses-material-design: true
